SELECT O.TURNO, O.Fecha,O.Ocupacion, E.NombreCompleto
FROM OCUPACIONES O, EMPLEADOS E 
WHERE O.IDEmpleado = E.ID AND E.NombreCompleto="Luis Franco";

SELECT * FROM ALEACIONES;
SELECT * FROM BRIQUETAS;
SELECT * FROM CALENDARIO;
SELECT * FROM EMPLEADOS;
SELECT * FROM OCUPACIONES;

CREATE TABLE Recursos(ID INT NOT NULL PRIMARY KEY, Codigo VARCHAR(50) NOT NULL, Nombe VARCHAR(150));
DROP TABLE Recursos;